import Footer from "./components/layouts/footer";
import Header from "./components/layouts/header";
import "./globals.css";

export const metadata = {
  title: "DoubledConG | 何聪聪",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
